### ISSUE TITLE
Updating the ipynb file to add text to make it more legible and accessible

### ISSUE THREAD

**Issue by LifeHashed** [Akasxh/Terrain-Recognition#2]
I want to add text in the notebook to make it more visually legible and can impart knowledge soundly

**Comment by Akasxh** [comment]
Sure after making necessary change, give me review request.

**Comment by DarshAgrawal14** [comment]
Hey I am Darsh Agrawal , a fellow contributor.
i would improve notebook readabolity by adding markdowns , commenting and adding stat analysis at different stages .
if you like my approach i would like to be assigned to given task

**Comment by Akasxh** [comment]
Hey Darsh, glad to hear about it. Please do add your markdowns and commenting.

If you want to add further EDA analysis, please do create another issue for it where I could provide you with sample dataset.

**Comment by DarshAgrawal14** [comment]
@Akasxh  i have added the markdowns and comments  for all the notebooks , regarding the EDA i would like to work on the next given issue first ..
and can you please add the level label for this issue?

**Comment by Akasxh** [comment]
If anything else please comment and create a seperate issue so that I could assign suitable labels and work. Thank you.
